---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.12-alpine3.9

inputs:
- name: master

params:
  AWS_ACCESS_KEY_ID:
  AWS_SCRET_ACCESS_KEY:

run:
  path: sh
  args:
  - -ec
  - |
    cd master
    apk add make cmake git wget
    make build
    tar czvf wawatwitterbot.tar.gz wawatweetbot quotes.txt
